# Лабораторная работа 1

## Правила

За разные задачи можно получить разное число баллов. Чтобы получить оценку 8, нужно предложить корректное решение задач №№1-7. Задача считается решённой, если код успешно проходит тесты и не содержит грубых нарушений. Задача 8 - бонус.

Во всех задачах для удобства проверки кода требуется написать функцию. Шаблон для функции уже написан, не меняйте её название, просто впишите свой код вместо ### YOUR CODE HERE и укажите название переменной с полученным результатом после return. Функции во всех задачах не должны ничего выводить на экран, после самопроверки уберите все конструкции с print(), если вы их использовали.

Работу нужно выполнить за пару и загрузить в LMS. Если вы хотите сдать работу позже в течение недели, ее максимальная оценка - 7. Через 2 недели - 6 (и т.д.).

In [ ]:
import numpy as np

### Задача 0. Пример решения, не оценивается

Напишите функцию get_size() , которая принимает на вход размер обуви size (целое положительное число) и возвращает размер туфель для скалолазания, учитывая, что обычно размер скальных туфель на два размера меньше обычного.

На входе:

```
37
```
На выходе:

```
35
```

In [ ]:
def get_size(size):

    return size - 2

Решение:

In [ ]:
def get_size(size):

    res = size - 2

    return res

Тесты (если всё верно, не выводится ничего, если ошибка – сообщение о неверном результате):

In [ ]:
assert get_size(36) == 34, "Неверный результат"
assert get_size(38) == 36, "Неверный результат"
assert get_size(40) == 38, "Неверный результат"
assert get_size(37) == 35, "Неверный результат"

### Задача 1. Температурный тренд (1 балл)

Дан массив `temperatures` – показания датчика температуры каждые 5 минут в течение нескольких часов (целые числа). Напишите функцию `trend(temps)`, которая принимает массив и возвращает массив той же длины, где каждый элемент – это знак изменения температуры по сравнению с предыдущим измерением:

- 1 – температура повысилась,
- -1 – понизилась,
- 0 – не изменилась.

Для первого элемента (нет предыдущего) верните 0.

Вход:
```
np.array([22, 23, 22, 22, 24])
```
Выход:
```
np.array([0, 1, -1, 0, 1])
```

In [5]:
def trend(temps):
    result = [0 if(ind == 0 or elem == temps[ind-1]) else 1 if(elem > temps[ind-1]) else -1 for ind,elem in enumerate(temps,start=0)]
    return result

In [6]:
import numpy as np
assert np.array_equal(trend(np.array([22, 23, 22, 22, 24])), np.array([0, 1, -1, 0, 1])), "Неверный результат"
assert np.array_equal(trend(np.array([18, 18, 20, 21, 20])), np.array([0, 0, 1, 1, -1])), "Неверный результат"
assert np.array_equal(trend(np.array([10, 12, 11, 11, 11])), np.array([0, 1, -1, 0, 0])), "Неверный результат"
assert np.array_equal(trend(np.array([24, 23, 23, 20, 20])), np.array([0, -1, 0, -1, 0])), "Неверный результат"

### Задача 2. Фильтрация данных (1 балл)

Датчик движения фиксирует наличие движения в комнате (1 – движение есть, 0 – нет). Дан массив `motion_data`. Напишите функцию `motion_periods(motion)`, которая принимает массив и возвращает количество непрерывных периодов движения (подряд идущих единиц), максимальную длительность периода и среднюю длительность периода. Одиночная единица тоже считается периодом.

Ответ верните в виде массива np

Вход:
```
np.array([0,1,1,0,0,1,0,1,1,1,0])
```
Выход:
```
np.array([3, 3, 2]) # количество, максимум, среднее
```
(периоды: [1,1], [1], [1,1,1])

In [30]:
def motion_periods(motion):
    last = 0
    s = 0
    count = 0
    max_duration = 0
    for idx, elem in enumerate(motion[1:],start=0):
        if(motion[idx] == 0 and elem == 1):
            last = idx
        if(motion[idx] == 1 and elem == 0):
            count += 1
            s += idx - last
            max_duration = max(max_duration,idx - last)
    if(motion[-1] == 1):
        count += 1
        s +=  len(motion) - last - 1
        max_duration = max(max_duration, len(motion) - last - 1)

    result = np.array([count,max_duration,s/count if count != 0 else 0])
    print(result)
    return result

In [31]:
assert np.array_equal(motion_periods(np.array([0,1,1,0,0,1,0,1,1,1,0])), np.array([3, 3, 2])), "Неверный результат"
assert np.array_equal(motion_periods(np.array([0,1,0,1,0,1,0,1,1,0,1])), np.array([5, 2, 1.2])), "Неверный результат"
assert np.array_equal(motion_periods(np.array([0,0,0,0,0,0,0,1,1,1,0])), np.array([1, 3, 3])), "Неверный результат"
assert np.array_equal(motion_periods(np.array([0,0,0,0,0,0,0,0,0])), np.array([0, 0, 0])), "Неверный результат"

[3. 3. 2.]
[5.  2.  1.2]
[1. 3. 3.]
[0 0 0]


### Задача 3. Ночной режим (1 балл)
Даны два массива одинаковой длины: `times` (время в часах от 0 до 23, целые) и `energy` (потребление энергии в кВт). Напишите функцию `night_energy(times, energy)`, которая возвращает среднее потребление энергии в ночные часы (с 23:00 до 5:00 включительно). Если в ночные часы нет данных, верните 0.0.

Вход:
```
times = np.array([0,3,6,9,12,15,18,21,23]),
energy = np.array([10,12,20,25,30,28,22,15,11])
```
Выход:
```
11.0
```

In [72]:
def night_energy(times, energy):
    mask =  times >= 23 
    mask2 = (0 <= times) & (times <= 5)
    masked_energy = energy[mask | mask2]
    if(len(masked_energy) == 0):
        return 0.0    
    return masked_energy.mean()

In [73]:
assert night_energy(np.array([0,3,6,9,12,15,18,21,23]), np.array([10,12,20,25,30,28,22,15,11])) == 11.0, "Неверный результат"
assert night_energy(np.array([6,7,8,9,10,11,12,13,14]), np.array([10,12,20,25,30,28,22,15,11])) == 0.0, "Неверный результат"
assert night_energy(np.array([3,5,7,9,11,13,15,17,19,21,23]), np.array([7,8,20,25,20,18,22,15,12,12,6])) == 7.0, "Неверный результат"
assert night_energy(np.array([0,1,2,3,4,5,6,7,8,9,10]), np.array([4,12,0,2,30,4,22,15,11,16,17])) == 8.666666666666666, "Неверный результат"

### Задача 4. Кодирование типов датчиков (1 балл)
В умном доме используются датчики трёх типов: "temperature", "humidity", "motion". Дан массив types (одномерный, тип object или str). Напишите функцию `encode_sensors(types)`, которая возвращает массив целых чисел той же длины, где:
- 0 для "temperature"
- 1 для "humidity"
- 2 для "motion"

Если встречается неизвестный тип, присвойте -1.

Вход:
```
np.array(["temperature", "motion", "humidity", "temperature"])
```
Выход:
```
np.array([0, 2, 1, 0])
```

In [ ]:
def encode_sensors(types):
    conditions = [types == "temperature", types =="motion", types == "humidity"]
    choices = [0,2,1]    
    result = np.select(conditions,choices,default = -1)
    return result


In [65]:
assert np.array_equal(encode_sensors(np.array(["temperature", "motion", "humidity", "temperature"])), np.array([0, 2, 1, 0])), "Неверный результат"
assert np.array_equal(encode_sensors(np.array(["temperature", "motion", "humidity", "alarm", "motion", "motion"])), np.array([0, 2, 1,-1, 2, 2])), "Неверный результат"
assert np.array_equal(encode_sensors(np.array(["alarm", "unknown"])), np.array([-1, -1])), "Неверный результат"
assert np.array_equal(encode_sensors(np.array(["motion", "motion", "humidity", "motion"])), np.array([2, 2, 1, 2])), "Неверный результат"

### Задача 5. Статистика по датчикам (1 балл)
Дан двумерный массив `sensor_data` размера n x m, где n – количество датчиков, m – количество временных срезов (каждый столбец – показания всех датчиков в момент времени). Напишите функцию `sensor_stats(data)`, которая возвращает массив размера n x 5 со следующими статистиками для каждого датчика (по строкам):

- минимум
- максимум
- среднее
- медиана
- стандартное отклонение

Все значения округлите до целого

Пример:
Вход:
```
np.array([[20,22,21], [45,47,46]])
```
Выход:
```
[[20.   22.   21.   21.   1.  ]
 [45.   47.   46.   46.   1.  ]]
 ```

In [92]:
def sensor_stats(data):
    result = np.array([[i.min(),i.max(),round(np.mean(i)),round(np.median(i)),round(i.std())] for i in data])
    return result
    

In [93]:
assert np.array_equal(sensor_stats(np.array([[20,22,21], [45,47,46]])), np.array([[20,22,21,21,1],[45,47,46,46,1]])), "Неверный результат"
assert np.array_equal(sensor_stats(np.array([[20,22,21,30], [45,47,46,50]])), np.array([[20,30,23,22,4],[45,50,47,46,2]])), "Неверный результат"
assert np.array_equal(sensor_stats(np.array([[20,22,21], [45,47,46], [10,10,11]])), np.array([[20,22,21,21,1],[45,47,46,46,1],[10,11,10,10,0]])), "Неверный результат"
assert np.array_equal(sensor_stats(np.array([[20,40,21]])), np.array([[20,40,27,21,9]])), "Неверный результат"

### Задача 6. Аномалии по IQR (1 балл)

Напишите функцию `find_outliers(data)`, которая принимает одномерный массив data (числа) и возвращает массив булевых значений той же длины, где True соответствует элементу, являющемуся выбросом по правилу IQR (межквартильный размах).

Границы: `[Q1 - 1.5*IQR, Q3 + 1.5*IQR]`

Используйте np.percentile.

Вход:
```
np.array([10,34,23,100,30,25,27,32])
```
Выход:
```
np.array([False, False, False, True, False, False, False, False])
```

In [125]:
def find_outliers(data):    
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    iqr = np.median(data) 
    mask1 = ((q1 - 1.5 * iqr) > data) 
    mask2 = data > q3 + 1.5 * iqr
    return (mask1 | mask2)

In [126]:
assert np.array_equal(find_outliers(np.array([10,34,23,100,30,25,27,32])), np.array([False,False,False,True,False,False,False,False])), "Неверный результат"
assert np.array_equal(find_outliers(np.array([15,34,23,99,19,101,27,14])), np.array([False,False,False,True,False,True,False,False])), "Неверный результат"
assert np.array_equal(find_outliers(np.array([15,34,23,40,19,39,27,12])), np.array([False,False,False,False,False,False,False,False])), "Неверный результат"
assert np.array_equal(find_outliers(np.array([115,134,23,140,119,39])), np.array([False,False,False,False,False,False])), "Неверный результат"

### Задача 7. СЛАУ (2 балла)

Решите систему линейных уравнений 3 разными способами (важно получить одинаковые результаты).

Пример:

$$
2x+3y=8
$$
$$
4x−y=6
​$$

Вход:
```
np.array([[2, 3],[4, -1]]
np.array([8, 6])
```

- стандартный метод – np.linalg.solve()
- метод Крамера – вычисление неизвестных через отношение определителей (замена столбцов матрицы A на вектор b)
- Метод обратной матрицы – умножение обратной матрицы A⁻¹ на b

Все результаты нужно округлить (до 2 знаков после запятой)

In [ ]:
def solve_method(A, b):
    result = np.linalg.solve(A,b)
    result = np.round(result,2)
    return result

In [159]:
assert np.array_equal(solve_method(np.array([[2, 3],[4, -1]]), np.array([8, 6])), np.array([1.86, 1.43])), "Неверный результат"
assert np.array_equal(solve_method(np.array([[1, 1, 1], [2, -1, 1], [1, 2, -1]]), np.array([6, 3, 2])), np.array([1, 2, 3])), "Неверный результат"
assert np.array_equal(solve_method(np.array([[2, 1, -1, 3], [1, -3, 2, 1], [3, 2, -2, -1], [-1, 4, 1, 2]]), np.array([9, -4, 5, 12])), np.array([0.82, 2.3 , 0.16, 1.74])), "Неверный результат"

[1.86 1.43]
[1. 2. 3.]
[0.82 2.3  0.16 1.74]


In [148]:
import copy
def cramer_method(A, b):
    """
    Решение СЛАУ методом Крамера.
    A - квадратная матрица коэффициентов (n x n)
    """
    d0 = np.linalg.det(A)
    res_array =[]
    for i in range(len(A)):
        new_matrix = copy.copy(A)
        new_matrix[:, i] = b
        res_array.append(round(np.linalg.det(new_matrix)/ d0,2))    
    return res_array 
    



In [149]:
assert np.array_equal(cramer_method(np.array([[2, 3],[4, -1]]), np.array([8, 6])), np.array([1.86, 1.43])), "Неверный результат"
assert np.array_equal(cramer_method(np.array([[1, 1, 1], [2, -1, 1], [1, 2, -1]]), np.array([6, 3, 2])), np.array([1, 2, 3])), "Неверный результат"
assert np.array_equal(cramer_method(np.array([[2, 1, -1, 3], [1, -3, 2, 1], [3, 2, -2, -1], [-1, 4, 1, 2]]), np.array([9, -4, 5, 12])), np.array([0.82, 2.3 , 0.16, 1.74])), "Неверный результат"

In [163]:
def inverse_matrix_method(A, b):
    """
    Решение СЛАУ через обратную матрицу
    """
    X = np.linalg.inv(A) @ b
    X = np.round(X,2)
    return X
    

In [164]:
assert np.array_equal(inverse_matrix_method(np.array([[2, 3],[4, -1]]), np.array([8, 6])), np.array([1.86, 1.43])), "Неверный результат"
assert np.array_equal(inverse_matrix_method(np.array([[1, 1, 1], [2, -1, 1], [1, 2, -1]]), np.array([6, 3, 2])), np.array([1, 2, 3])), "Неверный результат"
assert np.array_equal(inverse_matrix_method(np.array([[2, 1, -1, 3], [1, -3, 2, 1], [3, 2, -2, -1], [-1, 4, 1, 2]]), np.array([9, -4, 5, 12])), np.array([0.82, 2.3 , 0.16, 1.74])), "Неверный результат"

### Задача 8. Совместная активность (2 балла)

В умном доме несколько энергопотребителей (устройств). У каждого устройства есть список часов (0–23), в которые оно активно (например, обогреватель работает с 6 до 9 утра и с 18 до 22 вечера). Найдите устройства, которые у которых есть общие часы работы.

Вход:
```
devices = [
    ("Обогреватель", [6,7,8,9,18,19,20,21,22]),
    ("Электрочайник", [7,8,9,18,19,21]),
    ("Посудомойка", [22,23,2]),
    ("Стиральная машина", [10,11,12]),
    ("Освещение кухни", [18,19,20,21,22,2])
]
```
Выход:
```
[[0, 1, 1, 0, 1],
[1, 0, 0, 0, 1],
[1, 0, 0, 0, 1],
[0, 0, 0, 0, 0],
[1, 1, 1, 0, 0]]
 ```

*Пояснение*
- Обогреватель и чайник пересекаются по часам 7,8,9,18,19,21 → 1.
- Обогреватель и посудомойка пересекаются по часу 22 → 1.
- Обогреватель и освещение кухни пересекаются по часам 18–22 → 1.
- Чайник и освещение – по часам 18,19,21 → 1.
- Посудомойка и освещение – по часам 22,2 → 1.
- Стиральная машина не пересекается ни с кем → 0.
- Остальные пары – 0.

 Для нахождения всех уникальных пар значений можно воспользоваться функцией `combinations()` из модуля `itertools`. Пример:
```
from itertools import combinations
print(list(combinations([1, 2, 3], r = 2)))

[(1, 2), (1, 3), (2, 3)]
```

In [183]:
from itertools import combinations
def build_matrix(devices):
    n = len(devices)
    matrix = np.zeros((n,n))
    for i in combinations(range(n),2):
        if(len(set(devices[i[0]][1]) & set(devices[i[1]][1])) > 0):
            matrix[i[0]][i[1]] = 1
            matrix[i[1]][i[0]] = 1
    return matrix


In [182]:
assert np.array_equal(build_matrix([("Обогреватель", [6,7,8,9,18,19,20,21,22]),("Электрочайник", [7,8,9,18,19,21]), \
                    ("Посудомойка", [22,23,2]),("Стиральная машина", [10,11,12]),("Освещение кухни", [18,19,20,21,22,2])]), \
                    np.array([[0, 1, 1, 0, 1],[1, 0, 0, 0, 1],[1, 0, 0, 0, 1],[0, 0, 0, 0, 0],[1, 1, 1, 0, 0]])), "Неверный результат"
assert np.array_equal(build_matrix([("Электрочайник", [6,21]), ("Посудомойка", [21]),("Освещение кухни", [21,22,23]), ("Утюг", [6])]), \
                    np.array([[0, 1, 1, 1],[1, 0, 1, 0],[1, 1, 0, 0],[1, 0, 0, 0]])), "Неверный результат"
assert np.array_equal(build_matrix([("Электроплита", [6]), ("Посудомойка", [23]),("Освещение кухни", [21,22,23])]), \
                    np.array([[0, 0, 0],[0, 0, 1],[0, 1, 0]])), "Неверный результат"

[[0. 1. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
